### ISSUE TITLE
Logo on top of the nav bar or the level bar

### ISSUE THREAD

**Issue by meenal21** [Corruption13/ice-and-fire#2]
The ice and fire logo sits on top of the nav bar on the upper side of the screen, makes hard to rea - Level Complete or Level number.

Suggestions - extra space can be given to the ice and fire logo or it can be adjusted on the either side of the screen.

**Comment by Corruption13** [comment]
Hi Meenal!

Thank you for your feedback, yes it's a product of the low priority non-responsive frontend I cooked up on my 24-inch monitor. I should probably give a lower z-index and move it to the edge as you've suggested.

In the meantime, you can use the fullscreen button to expand the game fully so that no HTML divs come in the way of your game canvas.

I'll ship out an update with this fix and other levels by the end of the month, do take a look then!
![frontend on my device](https://user-images.githubusercontent.com/23308269/173247861-e2e7fadf-dec8-4d44-8384-3f03143782b0.png)

Thanks for playing <3

**Comment by Corruption13** [comment]
Issue Fixed in the latest patch.

Thank you.
